[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@octokit/rest", "openai"]

# Run the generator every day at 12:00 PM UTC
[[plugins]]
  package = "@netlify/plugin-functions-scheduled-jobs"

[[scheduled]]
  command = "/.netlify/functions/generate-threads"
  schedule = "0 12 * * *"
