[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@octokit/rest", "openai"]
  included_files = ["netlify/functions/package.json"]

[functions.generate-threads]
  schedule = "*/3 * * * *"
  timeout = 60

[[plugins]]
  package = "@netlify/plugin-functions-scheduled-jobs"
